// Get User Data Action //

export const GET_USER_PROGRESS = "GET_USER_PROGRESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

// Delete User  Action //

export const DELETE_USER_PROGRESS = "DELETE_USER_PROGRESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";

// Update User  Action //

export const UPDATE_USER_PROGRESS = "UPDATE_USER_PROGRESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

// Add User  Action //

export const ADD_USER_PROGRESS = "ADD_USER_PROGRESS";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

// Add PARTY  Action //

export const ADD_PARTY_PROGRESS = "ADD_PARTY_PROGRESS";
export const ADD_PARTY_SUCCESS = "ADD_PARTY_SUCCESS";
export const ADD_PARTY_ERROR = "ADD_PARTY_ERROR";

// GEt PARTY  Action //

export const GET_PARTY_PROGRESS = "GET_PARTY_PROGRESS";
export const GET_PARTY_SUCCESS = "GET_PARTY_SUCCESS";
export const GET_PARTY_ERROR = "GET_PARTY_ERROR";

// DELETE PARTY  Action //

export const DELETE_PARTY_PROGRESS = "DELETE_PARTY_PROGRESS";
export const DELETE_PARTY_SUCCESS = "DELETE_PARTY_SUCCESS";
export const DELETE_PARTY_ERROR = "DELETE_PARTY_ERROR";

// DELETE PARTY  Action //

export const UPDATE_PARTY_PROGRESS = "UPDATE_PARTY_PROGRESS";
export const UPDATE_PARTY_SUCCESS = "UPDATE_PARTY_SUCCESS";
export const UPDATE_PARTY_ERROR = "UPDATE_PARTY_ERROR";

// Add Election  Action //

export const Add_ELECTION_PROGRESS = "Add_ELECTION_PROGRESS";
export const Add_ELECTION_SUCCESS = "Add_ELECTION_SUCCESS";
export const Add_ELECTION_ERROR = "Add_ELECTION_ERROR";

// GET Elections  Action //

export const GET_ELECTION_PROGRESS = "GET_ELECTION_PROGRESS";
export const GET_ELECTION_SUCCESS = "GET_ELECTION_SUCCESS";
export const GET_ELECTION_ERROR = "GET_ELECTION_ERROR";

// DELETE Elections  Action //

export const DELETE_ELECTION_PROGRESS = "DELETE_ELECTION_PROGRESS";
export const DELETE_ELECTION_SUCCESS = "DELETE_ELECTION_SUCCESS";
export const DELETE_ELECTION_ERROR = "DELETE_ELECTION_ERROR";

// GET Votes  Action //

export const GET_VOTES_PROGRESS = "GET_VOTES_PROGRESS";
export const GET_VOTES_SUCCESS = "GET_VOTES_SUCCESS";
export const GET_VOTES_ERROR = "GET_VOTES_ERROR";

// Add PartyList  Action //

export const ADD_PARTYLIST_PROGRESS = "ADD_PARTYLIST_PROGRESS";
export const ADD_PARTYLIST_SUCCESS = "ADD_PARTYLIST_SUCCESS";
export const ADD_PARTYLIST_ERROR = "ADD_PARTYLIST_ERROR";

